# Generated by Django 5.1 on 2024-08-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Familiar',
        ),
    ]
